# Generated by Django 4.0.3 on 2022-04-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_interview', '0002_contact_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='exam_model',
            name='select_user',
        ),
    ]
